allow_anonymous false
persistence true
password_file /mosquitto/config/pwfile
persistence_file mosquitto.db
persistence_location /mosquitto/data/

listener 1883

# TLS
listener 8883
cafile /mosquitto/certs/rootCA-crt.pem
certfile /mosquitto/certs/server-crt.pem
keyfile /mosquitto/certs/server-key.pem

tls_version tlsv1.3
